### ISSUE TITLE
about mcg

### ISSUE THREAD

**Issue by GrassBro** [KuangJuiHsu/DeeoCO3#3]
Hi, @KuangJuiHsu ,

You compare your method with C2SNet, a saliency detection method, I, therefore, tried to reimplement the instance segmentation result based on the contour map(from C2SNet) and the MCG method. However, I met the problem that the contour map generated by C2SNet is different from the contour map of UCMs, which finally leads the MCG cannot generate segment proposals.

Could you give me any suggestions about your implementation detail?

Thanks in advance.
Xin

**Comment by KuangJuiHsu** [comment]
Hi, 
could you specify your problem in detail?

I just replac the contour maps of MCG with C2SNet to generate the proposal. You can trace the code of MCG.

I have the impression that it is straightforward to do it.

If you can't still solve problem, I can give this code but you may need to wait.

**Comment by GrassBro** [comment]
> Hi,
> could you specify your problem in detail?
> 
> I just replac the contour maps of MCG with C2SNet to generate the proposal. You can trace the code of MCG.
> 
> I have the impression that it is straightforward to do it.
> 
> If you can't still solve problem, I can give this code but you may need to wait.

I also tried to change the contour map directly. However, the contour map generated by C2SNet is relative thick than the original contour map from MCG, which makes the computation of segment proposals go in an endless loop. 

It is great if you can share the code to me. My email address is xtian@mail.dlut.edu.cn

Thanks.

**Comment by GrassBro** [comment]
hi, @KuangJuiHsu ,

Sorry for bothering you again. I would like to know when would be convenient for you to share the code to me.

**Comment by KuangJuiHsu** [comment]
Hi, 
I am sorry because I am busy now.

I can share the code before the end of Sep.

**Comment by GrassBro** [comment]
> Hi,
> I am sorry because I am busy now.
> 
> I can share the code before the end of Sep.

Thanks a lot.
