### ISSUE TITLE
Experiment Problem

### ISSUE THREAD

**Issue by huang1997214** [KuangJuiHsu/DeeoCO3#5]
I've run the demo for 22 categories. However, the result seems that there is a difference compared to your result. And I don't know my experiment's problem.

Thanks a lot!
![WeChat Image_20191027222529](https://user-images.githubusercontent.com/45142783/67647450-c748c380-f908-11e9-8589-0b575041e1d5.png)

**Comment by KuangJuiHsu** [comment]
Sorry, could you specify your setting? 

Before releasing the code, I actually run the code to ensure similar results with the released codes.

In addition, I run the code with Matlab on ubuntu 14.04.  Maybe the reason is the different OS.  You could try this code on ubuntu 14.04.

**Comment by huang1997214** [comment]
Thank you for your reply!
My setting is windows10 + Matlab2019 + VS2017 + matconvnet-1.0-beta25
Maybe it is the OS's problem. I will try it on ubuntu.
Thanks a lot!

**Comment by huang1997214** [comment]
Since the path is different in ubuntu and windows, I modify some code, maybe that's the problem.

**Comment by KuangJuiHsu** [comment]
Besides, I remember that I use Matlab 2018 a or b for the experiments, but this may not affect the results. 

I also use matconvnet-1.0-beta24 in "Lib". Maybe you could try this.

**Comment by huang1997214** [comment]
I will try it, thanks!

**Comment by KuangJuiHsu** [comment]
If any problem, welcome to ask, again.

**Comment by huang1997214** [comment]
Thanks！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Kuang-Jui Hsu <notifications@github.com>
发送时间: Monday, October 28, 2019 2:28:25 PM
收件人: KuangJuiHsu/DeepCO3 <DeepCO3@noreply.github.com>
抄送: Yifeng <huangyifeng1997214@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [KuangJuiHsu/DeepCO3] Experiment Problem (#5)


If any problem, welcome to ask, again.

―
